# Use a built-in Jekyll theme—no local gems needed
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme

# Your site’s information
title: "Luis Caicedo’s Math Musings"
description: "Reflections on math, AI, and life in research."
url: "https://cafecitocoma.github.io"
baseurl: ""  # no subpath

# Markdown & math support
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
mathjax:
  path: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
