# Tell GitHub Pages which theme to use
remote_theme: "mmistakes/minimal-mistakes"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-mathjax

# MathJax for LaTeX support
mathjax:
  path: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"

# Site metadata
title: "Luis Caicedo’s Math Musings"
description: "Reflections on math, physics-informed ML, and life in research."
url: "https://cafecitocoma.github.io"
author:
  name: "Luis Caicedo"
#  avatar: "/assets/images/penguin-logo.png"  # adjust or remove

# Optional: tweak colors/font schemes (see Minimal Mistakes docs)
# scheme: "default"
# header:
#   background: "#f5f5f5"

